# Generated by Django 5.1.1 on 2024-09-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
